# Generated by Django 4.0.3 on 2022-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Civil', 'Civil'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech')], max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
