# Generated by Django 4.0.3 on 2022-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('MINI_PROJECT', 'MINI_PROJECT'), ('FINAL_PROJECT', 'FINAL_PROJECT')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
