# Generated by Django 4.1.4 on 2023-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_category_alter_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batch',
            field=models.CharField(blank=True, choices=[('Civil', 'Civil'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('MINI_PROJECT', 'MINI_PROJECT'), ('FINAL_PROJECT', 'FINAL_PROJECT'), ('HACKAHTON_PROJECT', 'HACKAHTON_PROJECT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
